# Custom config for scss-lint
# Find an example of all options here: https://github.com/causes/scss-lint/blob/master/config/default.yml

exclude:
    - 'style.css'
    - 'vendor/**'

linters:
  Indentation:
    enabled: true
    width: 4

  PropertySortOrder:
    order: ['display', 'overflow', 'box-sizing', 'width', 'max-width', 'height', 'max-height', 'padding', 'border', 'margin', 'margin-left', 'background', 'background-image', 'background-repeat', 'background-size', 'background-position', 'color', 'font-family', 'font-size', 'line-height', 'text-align', 'cursor']

  SelectorDepth:
    enabled: true
    max_depth: 4

  StringQuotes:
    style: double_quotes

  NameFormat:
    enabled: false
    convention: BEM

  TrailingSemicolonAfterPropertyValue:
    enabled: false
    
    position: absolute;
  z-index: 10;
  top: 0;
  right: 0;
